// SPDX-License-Identifier: MIT
//
// grammar_rocq.c — hand-authored tree-sitter TSLanguage for Rocq.
//
// Original work. Unlike the other vendored grammars, this is NOT generated by
// the tree-sitter CLI from a grammar.js — there are no parse/lex tables here.
// Our pure-C parser builds the TSTree directly (see rocq/rocq_tree.*), so the
// runtime never runs a table-driven parse; it only *walks* the tree. Walking
// needs just the symbol names/metadata and field maps, which we provide here.
// The node-type/field/production ids come from rocq/rocq_cst.h.
#include "rocq/rocq_cst.h"
#include "rocq/rocq_tree.h"
#include "tree_sitter/api.h" // must precede parser.h: parser.h skips TSLanguageMetadata if api.h seen
#include "parser.h" // tree-sitter runtime: TSLanguage, TSSymbolMetadata, TSFieldMapEntry, TSMapSlice
#include "length.h"
#include "subtree.h"
#include "tree.h"
#include "array.h"

#include <stdbool.h>
#include <stdlib.h>

// Node-type names, indexed by RocqSymbol.
static const char *const rocq_symbol_names[RSYM_COUNT] = {
    [RSYM_END] = "end",
    [RSYM_SOURCE_FILE] = "source_file",
    [RSYM_COMMENT] = "comment",
    [RSYM_IDENT] = "identifier",
    [RSYM_QUALID] = "qualified_identifier",
    [RSYM_NUMBER] = "number",
    [RSYM_STRING] = "string",
    [RSYM_OPERATOR] = "operator",
    [RSYM_TERM] = "term",
    [RSYM_DEFINITION] = "definition",
    [RSYM_THEOREM] = "theorem",
    [RSYM_INDUCTIVE] = "inductive",
    [RSYM_CONSTRUCTOR] = "constructor",
    [RSYM_RECORD] = "record",
    [RSYM_FIELD_DEF] = "field",
    [RSYM_CLASS] = "typeclass",
    [RSYM_INSTANCE] = "instance",
    [RSYM_MODULE] = "module",
    [RSYM_MODULE_TYPE] = "module_type",
    [RSYM_SECTION] = "section",
    [RSYM_REQUIRE] = "require",
    [RSYM_IMPORT] = "import",
    [RSYM_NOTATION] = "notation",
    [RSYM_TACTIC] = "tactic_notation",
    [RSYM_ASSUMPTION] = "assumption",
    [RSYM_PROOF] = "proof",
    [RSYM_COERCION] = "coercion",
    [RSYM_GENERIC] = "command",
};

// Every Rocq symbol is a visible, named node (we emit no anonymous tokens; the
// command keyword is encoded in the node type, not a child token).
static const TSSymbolMetadata rocq_symbol_metadata[RSYM_COUNT] = {
    [RSYM_END] = {.visible = false, .named = false, .supertype = false},
    [RSYM_SOURCE_FILE] = {.visible = true, .named = true, .supertype = false},
    [RSYM_COMMENT] = {.visible = true, .named = true, .supertype = false},
    [RSYM_IDENT] = {.visible = true, .named = true, .supertype = false},
    [RSYM_QUALID] = {.visible = true, .named = true, .supertype = false},
    [RSYM_NUMBER] = {.visible = true, .named = true, .supertype = false},
    [RSYM_STRING] = {.visible = true, .named = true, .supertype = false},
    [RSYM_OPERATOR] = {.visible = true, .named = true, .supertype = false},
    [RSYM_TERM] = {.visible = true, .named = true, .supertype = false},
    [RSYM_DEFINITION] = {.visible = true, .named = true, .supertype = false},
    [RSYM_THEOREM] = {.visible = true, .named = true, .supertype = false},
    [RSYM_INDUCTIVE] = {.visible = true, .named = true, .supertype = false},
    [RSYM_CONSTRUCTOR] = {.visible = true, .named = true, .supertype = false},
    [RSYM_RECORD] = {.visible = true, .named = true, .supertype = false},
    [RSYM_FIELD_DEF] = {.visible = true, .named = true, .supertype = false},
    [RSYM_CLASS] = {.visible = true, .named = true, .supertype = false},
    [RSYM_INSTANCE] = {.visible = true, .named = true, .supertype = false},
    [RSYM_MODULE] = {.visible = true, .named = true, .supertype = false},
    [RSYM_MODULE_TYPE] = {.visible = true, .named = true, .supertype = false},
    [RSYM_SECTION] = {.visible = true, .named = true, .supertype = false},
    [RSYM_REQUIRE] = {.visible = true, .named = true, .supertype = false},
    [RSYM_IMPORT] = {.visible = true, .named = true, .supertype = false},
    [RSYM_NOTATION] = {.visible = true, .named = true, .supertype = false},
    [RSYM_TACTIC] = {.visible = true, .named = true, .supertype = false},
    [RSYM_ASSUMPTION] = {.visible = true, .named = true, .supertype = false},
    [RSYM_PROOF] = {.visible = true, .named = true, .supertype = false},
    [RSYM_COERCION] = {.visible = true, .named = true, .supertype = false},
    [RSYM_GENERIC] = {.visible = true, .named = true, .supertype = false},
};

// Identity public-symbol map (we expose internal symbols directly).
static const TSSymbol rocq_public_symbol_map[RSYM_COUNT] = {
    0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13,
    14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
};

// Alias map: none (one entry per symbol, all zero = no aliases).
static const TSSymbol rocq_alias_map[1] = {0};

// Alias sequences: we use no child aliases, but a TSTreeCursor reads
// alias_sequences[production_id * max_alias_sequence_length + child_index] for
// every visited child, so this must be a valid (zero) array large enough for the
// field-bearing productions' bounded child counts. Variable-arity nodes use
// production 0 (RPROD_NONE), for which the lookup short-circuits to 0.
enum { ROCQ_MAX_ALIAS_SEQ_LEN = 3 };
static const TSSymbol rocq_alias_sequences[RPROD_COUNT * ROCQ_MAX_ALIAS_SEQ_LEN] = {0};

// Field names, indexed by RocqField (index 0 unused).
static const char *const rocq_field_names[RFLD_COUNT] = {
    [RFLD_NONE] = (void *)0,
    [RFLD_NAME] = "name",
    [RFLD_TYPE] = "type",
    [RFLD_BODY] = "body",
    [RFLD_CLASS] = "class",
    [RFLD_PATTERN] = "pattern",
};

// Field-map entries, grouped by production and sorted by field id within each.
// Entries within each production's slice MUST be sorted by field_id ascending
// (the runtime narrows the slice by field_id). child_index is the structural
// index of the field's child within the node.
static const TSFieldMapEntry rocq_field_map_entries[] = {
    // RPROD_NAME (index 0, len 1)
    {RFLD_NAME, 0, false},
    // RPROD_NAME_TYPE (index 1, len 2): NAME(3) < TYPE(5)
    {RFLD_NAME, 0, false},
    {RFLD_TYPE, 1, false},
    // RPROD_INSTANCE (index 3, len 2): CLASS(2) < NAME(3)
    {RFLD_CLASS, 1, false},
    {RFLD_NAME, 0, false},
    // RPROD_NOTATION (index 5, len 1)
    {RFLD_PATTERN, 0, false},
};

static const TSMapSlice rocq_field_map_slices[RPROD_COUNT] = {
    [RPROD_NONE] = {0, 0},
    [RPROD_NAME] = {0, 1},
    [RPROD_NAME_TYPE] = {1, 2},
    [RPROD_INSTANCE] = {3, 2},
    [RPROD_NOTATION] = {5, 1},
};

static const TSLanguage rocq_language = {
    .abi_version = 14, // < LANGUAGE_VERSION_WITH_RESERVED_WORDS (15): no metadata/name required
    .symbol_count = RSYM_COUNT,
    .alias_count = 0,
    .token_count = RSYM_TERM, // symbols below RSYM_TERM are terminals
    .external_token_count = 0,
    .state_count = 0,
    .large_state_count = 0,
    .production_id_count = RPROD_COUNT,
    .field_count = RFLD_COUNT - 1,
    .max_alias_sequence_length = ROCQ_MAX_ALIAS_SEQ_LEN,
    .parse_table = (void *)0,
    .small_parse_table = (void *)0,
    .small_parse_table_map = (void *)0,
    .parse_actions = (void *)0,
    .symbol_names = rocq_symbol_names,
    .field_names = rocq_field_names,
    .field_map_slices = rocq_field_map_slices,
    .field_map_entries = rocq_field_map_entries,
    .symbol_metadata = rocq_symbol_metadata,
    .public_symbol_map = rocq_public_symbol_map,
    .alias_map = rocq_alias_map,
    .alias_sequences = rocq_alias_sequences,
    .lex_modes = (void *)0,
    .lex_fn = (void *)0,
    .keyword_lex_fn = (void *)0,
    .keyword_capture_token = 0,
    .primary_state_ids = (void *)0,
    .name = "rocq",
};

const TSLanguage *tree_sitter_rocq(void) { return &rocq_language; }

// ── Tree builder ──────────────────────────────────────────────────────────
// Constructs a real tree-sitter TSTree from the parser's open/leaf/close calls.

typedef struct {
    TSSymbol sym;
    uint32_t prod;
    SubtreeArray children;
} RocqFrame;

struct RocqTreeBuilder {
    const char *src;
    uint32_t len;
    uint32_t cursor; // byte offset consumed so far (token starts compute padding from here)
    SubtreePool pool;
    RocqFrame *frames;
    int nframes;
    int cap;
};

// tree-sitter Length for [from,to): bytes + extent (rows = newlines, column =
// bytes after the last newline, in bytes).
static Length rocq_span(const char *src, uint32_t from, uint32_t to) {
    Length l;
    l.bytes = to - from;
    uint32_t rows = 0;
    uint32_t last_nl_end = from;
    for (uint32_t i = from; i < to; i++) {
        if (src[i] == '\n') {
            rows++;
            last_nl_end = i + 1;
        }
    }
    l.extent.row = rows;
    l.extent.column = rows ? (to - last_nl_end) : (to - from);
    return l;
}

static void rocq_tb_push_frame(RocqTreeBuilder *b, TSSymbol sym, uint32_t prod) {
    if (b->nframes >= b->cap) {
        int nc = b->cap ? b->cap * 2 : 16;
        RocqFrame *nf = (RocqFrame *)realloc(b->frames, (size_t)nc * sizeof(*nf));
        if (!nf) {
            return;
        }
        b->frames = nf;
        b->cap = nc;
    }
    RocqFrame f = {.sym = sym, .prod = prod}; // children zero-inits to an empty Array
    b->frames[b->nframes++] = f;
}

RocqTreeBuilder *rocq_tb_new(const char *source, int source_len) {
    RocqTreeBuilder *b = (RocqTreeBuilder *)calloc(1, sizeof(*b));
    if (!b) {
        return NULL;
    }
    b->src = source;
    b->len = source_len > 0 ? (uint32_t)source_len : 0;
    b->cursor = 0;
    // Open the implicit root frame before creating the subtree pool: if its
    // allocation fails (OOM) we bail here, before any ts_runtime allocation.
    rocq_tb_push_frame(b, RSYM_SOURCE_FILE, RPROD_NONE);
    if (b->nframes == 0) {
        free(b->frames);
        free(b);
        return NULL;
    }
    b->pool = ts_subtree_pool_new(64);
    return b;
}

// Precondition (guaranteed by the parser, the sole caller): the builder is valid
// with the root frame open, and leaves arrive in non-decreasing byte order with
// end_byte >= start_byte. No defensive validation is performed.
void rocq_tb_leaf(RocqTreeBuilder *b, RocqSymbol sym, uint32_t start_byte, uint32_t end_byte) {
    Length padding = rocq_span(b->src, b->cursor, start_byte);
    Length size = rocq_span(b->src, start_byte, end_byte);
    Subtree leaf = ts_subtree_new_leaf(&b->pool, (TSSymbol)sym, padding, size, 0, 0, false, false,
                                       false, &rocq_language);
    array_push(&b->frames[b->nframes - 1].children, leaf);
    b->cursor = end_byte;
}

void rocq_tb_open(RocqTreeBuilder *b, RocqSymbol sym, RocqProduction prod) {
    rocq_tb_push_frame(b, (TSSymbol)sym, (uint32_t)prod);
}

void rocq_tb_close(RocqTreeBuilder *b) {
    if (b->nframes <= 1) {
        // Nothing to close but the implicit root — e.g. an `End.` with no open
        // module/section, which the parser dispatches unconditionally.
        return;
    }
    RocqFrame f = b->frames[--b->nframes];
    if (f.children.size == 0) {
        // Drop empty nodes (e.g. a `term`/`proof` that captured no tokens) rather
        // than emit a zero-width named node. An empty frame never grew its children
        // array (size 0 ⇒ no array_push ⇒ contents NULL), so there is nothing to free.
        return;
    }
    MutableSubtree node = ts_subtree_new_node((TSSymbol)f.sym, &f.children, f.prod, &rocq_language);
    array_push(&b->frames[b->nframes - 1].children, ts_subtree_from_mut(node));
}

void *rocq_tb_finish(RocqTreeBuilder *b) {
    while (b->nframes > 1) { // close any unbalanced open nodes (e.g. unterminated module)
        rocq_tb_close(b);
    }
    RocqFrame f = b->frames[0];
    b->nframes = 0;
    MutableSubtree root = ts_subtree_new_node((TSSymbol)f.sym, &f.children, f.prod, &rocq_language);
    // Pass tree-sitter's default whole-document included range (as ts_parser
    // does) rather than NULL/0 — ts_tree_new memcpy's the ranges unconditionally,
    // and a NULL source trips the runtime's nonnull contract.
    static const TSRange full_range = {
        .start_point = {0, 0},
        .end_point = {0xFFFFFFFFu, 0xFFFFFFFFu},
        .start_byte = 0,
        .end_byte = 0xFFFFFFFFu,
    };
    TSTree *tree = ts_tree_new(ts_subtree_from_mut(root), &rocq_language, &full_range, 1);
    return tree;
}

void rocq_tb_free(RocqTreeBuilder *b) {
    ts_subtree_pool_delete(&b->pool);
    free(b->frames);
    free(b);
}

void rocq_tree_free(void *tree) {
    if (tree) {
        ts_tree_delete((TSTree *)tree);
    }
}
